// Angular2/components/src/app/productList/filtProductTable/productTable/productRow/productRow.component.ts
import { Component, Input } from '@angular/core';

import { ProductClass } from '../../../productClass';

@Component({
    moduleId: module.id,
    selector: 'productRow',
    templateUrl: './productRow.component.html',
    styleUrls: ['./productRow.component.css']
})

export class ProductRowComponent {

    @Input() product: ProductClass;

    constructor() {

    }

}

<div class="card-group">
    <div class="card">
        <div class="card-block">
            <h6 [style.color]="product.stocked ? 'black' : 'red'">{{product.name}}</h6>
        </div>
    </div>
    <div class="card">
        <div class="card-block">
            <h6>{{product.price}}</h6>
        </div>
    </div>
</div>

// React/components/src/components/ProductList/FiltProductTable/ProductTable/ProductRow/ProductRow.js
'use strict';

var React = require('react');

var ProductRow = React.createClass({
    render: function() {
        var name = this.props.product.stocked ?
            this.props.product.name :
            <span style={{color: 'red'}}>
        {this.props.product.name}
      </span>;
        return (
            <tr>
                <td>{name}</td>
                <td>{this.props.product.price}</td>
            </tr>
        );
    }
});



module.exports = ProductRow;
