// React/components/src/components/ProductList/FiltProductTable/ProductTable/ProductTable.js
'use strict';

var React = require('react');
var ProductCategoryRow = require('./ProductCategoryRow/ProductCategoryRow');
var ProductRow = require('./ProductRow/ProductRow');

var ProductTable = React.createClass({
    render: function () {
        var rows = [];
        var lastCategory = null;
        this.props.products.forEach(function (product) {
            if (product.category !== lastCategory) {
                rows.push(<ProductCategoryRow category={product.category} key={product.category}/>);
            }
            rows.push(<ProductRow product={product} key={product.name}/>);
            lastCategory = product.category;
        });
        return (
            <div>
                <table className="table table-bordered table-hover">
                    <thead>
                    <tr className="info">
                        <th>Name</th>
                        <th>Price</th>
                    </tr>
                    </thead>
                    <tbody>
                    {rows}
                    </tbody>
                </table>
            </div>
        );
    }
});

module.exports = ProductTable;

// Angular2/components/src/app/productList/filtProductTable/productTable/productTable.component.ts
import { Component, Input } from '@angular/core';

import { ProductClass } from '../../product-class';

@Component({
    moduleId: module.id,
    selector: 'productTable',
    templateUrl: './productTable.component.html',
    styleUrls: ['./productTable.component.css']
})

export class ProductTableComponent {

    @Input() products: ProductClass[];

    constructor() {

    }

}

<table class="table table-bordered table-hover">
    <thead>
    <tr class="table-info">
        <th>Name</th>
        <th>Price</th>
    </tr>
    </thead>
    <tbody ng-init="lastCategory = '' ">
    <tr *ngFor="let product of products">
        <td>{{product.name}}</td><td>{{product.price}}</td>
    </tr>
    </tbody>
</table>
