// React/components/src/components/ProductList/FiltProductTable/SearchBar/SearchBar.js
'use strict';

var React = require('react');

var SearchBar = React.createClass({
    render: function () {
        return (
            <div>
                <form>
                    <input type="text" className="form-control" placeholder="Search..."/>
                    <div className="checkbox">
                        <label><input type="checkbox" value="">Only show products in stock</input></label>
                    </div>
                </form>
            </div>
        );
    }
});


module.exports = SearchBar;

// Angular2/components/src/app/productList/filtProductTable/searchBar/searchBar.component.ts
import { Component } from '@angular/core';

@Component({
    moduleId: module.id,
    selector: 'searchBar',
    templateUrl: './searchBar.component.html',
    styleUrls: ['./searchBar.component.css']
})

export class SearchBarComponent {

    constructor() {

    }

}

<form>
    <input type="text" class="form-control" placeholder="Search..." id="filterTextInput" />
    <label class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input">
        <span class="custom-control-indicator"></span>
        <span class="custom-control-description">Only show products in stock</span>
    </label>
</form>
